USE [master]
GO

/****** Object:  Database [HelpYouDB]    Script Date: 6/13/2017 7:31:34 PM ******/
CREATE DATABASE [HelpYouDB]
 CONTAINMENT = NONE
 ON  PRIMARY /*IMPORTANTE CAMBIAR EL PATH A DONDE QUIERES LA BASE DE DATOS*/
( NAME = N'HelpYouDB', FILENAME = N'D:\DB\HelpYou\HelpYouDB.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HelpYouDB_log', FILENAME = N'D:\DB\HelpYou\HelpYouDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HelpYouDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HelpYouDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HelpYouDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HelpYouDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HelpYouDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HelpYouDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HelpYouDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [HelpYouDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HelpYouDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [HelpYouDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HelpYouDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HelpYouDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HelpYouDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HelpYouDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HelpYouDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HelpYouDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HelpYouDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HelpYouDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HelpYouDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HelpYouDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HelpYouDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HelpYouDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HelpYouDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HelpYouDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HelpYouDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HelpYouDB] SET RECOVERY FULL 
GO

ALTER DATABASE [HelpYouDB] SET  MULTI_USER 
GO

ALTER DATABASE [HelpYouDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HelpYouDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HelpYouDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HelpYouDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HelpYouDB] SET  READ_WRITE 
GO


